name: Docker image
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
    Docker-image:
      runs-on: ubuntu-latest
      needs: [clone down repository]
      permissions:
      packages: write
    env:
      docker_username:  docker_username: ${{ github.actor }} 
      docker_password: ${{ secrets.GITHUB_TOKEN }} #Nees to be set to be made available to the workflow
      #GIT_COMMIT: github.sha
