name: Main workflow

# Triggers the workflow on push 
on: [workflow_dispatch] #push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Creates a container, which is teared down after run.
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4  
        # Run commands
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
